name: "Deploy to aws"

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6

      - name: "Setup nodejs"
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: "Install dependencies"
        run: npm install
        working-directory: ./todo-frontend

      - name: "Run the tests"
        run: npm test
        working-directory: ./todo-backend

      - name: "Deploy to aws"
        run: pm2 restart start.js
        working-directory: ./todo-backend