name: Deploy to AWS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./todo-frontend

      - name: Build frontend
        run: npm run build
        working-directory: ./todo-frontend

      - name: Install backend dependencies
        run: npm install
        working-directory: ./todo-backend

      - name: Run backend tests
        run: npm test
        working-directory: ./todo-backend

      - name: Deploy application
        run: |
          pm2 restart all
        working-directory: ./todo-backend